### ISSUE TITLE
Random Option?

### ISSUE THREAD

**Issue by itsjop** [lmcintyre/PrefPro#1]
Hey there! I love the idea of your plugin, and it's a great quality of life feature! I play a rather androgynous character, and I would absolutely _love_ an option to add a third option for `random` in the pluginUI like so:
```
 if (ImGui.BeginCombo("##prefProComboBox:", currentGender))
   {
        if (ImGui.Selectable("Male"))
            configuration.SelectedGender = "Male";
        if (ImGui.Selectable("Female"))
            configuration.SelectedGender = "Female";
        if (ImGui.Selectable("Random"))
            configuration.SelectedGender = "Random";
        configuration.Save();
        ImGui.EndCombo();
    }
```
That way when PlayerGender is getting referenced in the `PrefPro.cs` where `LocalPlayer?.Customize[(int)CustomizeIndex.Gender]` is being assigned, it could use a check on something akin to
`public string PlayerGender = new Random().next(0,1) == 1 ? 'Male' : 'Female' ` to return the desired noun. I'm not entirely sure of the framework behind the scenes on how that method would be _called_ to update the pronoun value - whether it can run on a random timer to re-call the random name function, or if it'd have to be run on GUI update - but regardless, I'd be delighted to see a small tweak like this implemented. I'd make a pull request, but C# isn't exactly my native tongue and it might end up more work for both of us untangling that.

Thanks!

**Comment by lmcintyre** [comment]
Sorry for leaving you hanging for so long. This feature made its way into version 1.1.0.0, currently released as a testing release. Thank you for the suggestion!
