### ISSUE TITLE
Race in SHB

### ISSUE THREAD

**Issue by lael-i** [lmcintyre/PrefPro#14]
Hi, I started Shadowbringers today and in the quest City of the First some dialogue comes up that references your race. I had not realised until now that the plugin had updated to include race customisation, but on checking it my character's had been set automatically to Au Ra (though incorrectly as Raen rather than Xaela). However, the dialogue failed to find it entirely;

![image](https://github.com/lmcintyre/PrefPro/assets/68711143/3d911c40-a99c-4fb8-a3dd-b50d8a35c00b)
![image](https://github.com/lmcintyre/PrefPro/assets/68711143/1b47fdf5-e3e7-454c-8df5-ad9add62e609)

**Comment by lmcintyre** [comment]
This is likely fixed with the latest version. Thank you for your report!
