### ISSUE TITLE
Implement to change gender on VA lines

### ISSUE THREAD

**Issue by thakyZ** [lmcintyre/PrefPro#3]
I would love to see if there was implementation of voice acted lines to have a different gender. At the moment, if I have the gender set to "Male" and the text reads "him", the voice acting will still say "her", as I have a female character. I do not know how easy this would be to implement, but I would love to see it done.

**Comment by lmcintyre** [comment]
Sorry for the late response. Going through all issues.

This is planned, but the voice lines are a bit more complex than the text, so it may take a while.

**Comment by thakyZ** [comment]
That's okay, I am happy to hear it's planned.

**Comment by lmcintyre** [comment]
This should be functioning on version 1.2.0.0, which should be live on Dalamud for plugin testers soon.

**Comment by thakyZ** [comment]
I can confirm it works!
