### ISSUE TITLE
Usable on CN server?

### ISSUE THREAD

**Issue by CrystalineIxia** [lmcintyre/PrefPro#4]
This is a surprisingly useful plugin!! Super super niche request I guess. But is it possible to make it compatible with CN server too? I think some CN server users like me would appreciate it.

A couple issues: CN server only has one name field. It probably have a different payload byte address but I'm not sure. Currently it crashes on initialization. If you could point at a way for me to dig through the CN client I would gladly do it. 

Thanks!

**Comment by CrystalineIxia** [comment]
I just realized, even before that request, the Name changer only care about ASCII characters... Maybe this is a way larger effort than I initially imagined...

**Comment by lmcintyre** [comment]
I can add support for non-ASCII names soon and see if that solves the issue here. However, I will not be able to do the research for CN as testing would require connecting to CN servers.
