### ISSUE TITLE
Implement gender neutral option?

### ISSUE THREAD

**Issue by ratheralarming** [lmcintyre/PrefPro#5]
Hello!

I love the hell out of this plugin-- especially the random gender option-- but I was wondering if it was in the cards to possibly implement a gender neutral / they/them option. I am guessing that switching between genders isn't adding new text but rather pulling on the appropriate text option? But I figured I'd ask anyway, and if it's a no, I can show my appreciation for your hard work! Thank you so much for this amazing option :D

**Comment by lmcintyre** [comment]
I would love to, but the game's writing comes with male and female dialogue built-in. Genderless dialogue would require practically a rewrite of the entire game, as the gendered language is not always just a pronoun here and there, but may completely change the dialogue in some cases. It is unfortunately way past the scope of this plugin to rewrite the entire game's quest dialogue.
